spring:
  profiles.active: mysql, integration
app:
  name: SimpleWebApp
  description: SimpleWebApp is a Spring Boot application

---

spring:
  profiles: integration
app:
  name: SimpleWebApp
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:/localhost:3306/simpledb_int
  username: simpledb_int
  password: simpledb_int
spring.jpa:
  show-sql: true
spring.jpa.hibernate:
  ddl-auto: verify
spring.jpa:
  show-sql: true
spring.jpa.hibernate:
  ddl-auto: validate

---

spring:
  profiles: uat
app:
  name: SimpleWebApp (UAT)
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:/localhost:3306/simpledb_uat
  username: simpledb_uat
  password: simpledb_uat
spring.jpa:
  show-sql: false
spring.jpa.hibernate:
  ddl-auto: verify
spring.jpa:
  show-sql: false
spring.jpa.hibernate:
  ddl-auto: validate

---

spring:
  profiles: ppro
app:
  name: SimpleWebApp (OAT)
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:/localhost:3306/simpledb_ppro
  username: simpledb_ppro
  password: simpledb_ppro
spring.jpa:
  show-sql: false
spring.jpa.hibernate:
  ddl-auto: validate

---

spring:
  profiles: production
app:
  name: SimpleWebApp (Production)
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:/localhost:3306/simpledb_prod
  username: simpledb_prod
  password: simpledb_prod
spring.jpa:
  show-sql: false
spring.jpa.hibernate:
  ddl-auto: validate

---

spring:
  profiles: mysql
app:
  name: SimpleWebApp (MySQL)
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/simpledb_int
  username: simpledb_int
  password: simpledb_int
spring.jpa:
  database: MYSQL
  show-sql: true
spring.jpa.hibernate:
  ddl-auto: update
  dialect: org.hibernate.dialect.MySQLDialect
  naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy